// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

export interface InsertadoptionRequests {
	userId: string
	animalId: string
	status?: 'pending' | 'approved' | 'rejected' | 'completed'
	message?: string
	hasExperience?: boolean
	hasOtherPets?: boolean
	hasChildren?: boolean
	houseType?: string
	feedback?: string
	requestedAt?: Date
	respondedAt?: Date
	completedAt?: Date
}
export interface UpdateadoptionRequests {
	userId?: string
	animalId?: string
	status?: 'pending' | 'approved' | 'rejected' | 'completed'
	message?: string
	hasExperience?: boolean
	hasOtherPets?: boolean
	hasChildren?: boolean
	houseType?: string
	feedback?: string
	requestedAt?: Date
	respondedAt?: Date
	completedAt?: Date
}
export interface SelectadoptionRequests {
	id: string
	userId: string
	animalId: string
	status: 'pending' | 'approved' | 'rejected' | 'completed'
	message?: string
	hasExperience?: boolean
	hasOtherPets?: boolean
	hasChildren?: boolean
	houseType?: string
	feedback?: string
	requestedAt: Date
	respondedAt?: Date
	completedAt?: Date
}
