// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

export interface Insertanimals {
	shelterId?: string
	userId?: string
	name: string
	type: 'dog' | 'cat' | 'other'
	breed?: string
	age?: number
	size: 'small' | 'medium' | 'big'
	gender: 'male' | 'female'
	color?: string
	description?: string
	healthInfo?: string
	adoptionReason?: string
	isAdopted?: boolean
	imageUrl?: string
	createdAt?: Date
	updatedAt?: Date
}
export interface Updateanimals {
	shelterId?: string
	userId?: string
	name?: string
	type?: 'dog' | 'cat' | 'other'
	breed?: string
	age?: number
	size?: 'small' | 'medium' | 'big'
	gender?: 'male' | 'female'
	color?: string
	description?: string
	healthInfo?: string
	adoptionReason?: string
	isAdopted?: boolean
	imageUrl?: string
	createdAt?: Date
	updatedAt?: Date
}
export interface Selectanimals {
	id: string
	shelterId?: string
	userId?: string
	name: string
	type: 'dog' | 'cat' | 'other'
	breed?: string
	age?: number
	size: 'small' | 'medium' | 'big'
	gender: 'male' | 'female'
	color?: string
	description?: string
	healthInfo?: string
	adoptionReason?: string
	isAdopted: boolean
	imageUrl?: string
	createdAt: Date
	updatedAt: Date
}
