// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

export interface Insertshelters {
	name: string
	email: string
	phone: string
	cnpj?: string
	description?: string
	address: string
	city: string
	state: string
	zipCode: string
	website?: string
	createdAt?: Date
	updatedAt?: Date
}
export interface Updateshelters {
	name?: string
	email?: string
	phone?: string
	cnpj?: string
	description?: string
	address?: string
	city?: string
	state?: string
	zipCode?: string
	website?: string
	createdAt?: Date
	updatedAt?: Date
}
export interface Selectshelters {
	id: string
	name: string
	email: string
	phone: string
	cnpj?: string
	description?: string
	address: string
	city: string
	state: string
	zipCode: string
	website?: string
	createdAt: Date
	updatedAt: Date
}
