import {
	InsertAdoptionRequestsSchema,
	SelectAdoptionRequestsSchema,
	UpdateAdoptionRequestsSchema,
} from 'src/lib/validators'
import { z } from 'zod'
// Generated by @drzl/generator-orpc
// Router for table: adoption_requests
import { AdoptionRequestService } from '@/lib/services/adoption-request-service'
import { protectedProcedure } from '../..'

const listAdoptionRequests = protectedProcedure()
	.output(z.array(SelectAdoptionRequestsSchema))
	.handler(async () => {
		return await AdoptionRequestService.getAll()
	})

const getAdoptionRequests = protectedProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(SelectAdoptionRequestsSchema.nullable())
	.handler(async ({ input }) => {
		return await AdoptionRequestService.getById(input.id)
	})

const createAdoptionRequests = protectedProcedure()
	.input(InsertAdoptionRequestsSchema)
	.output(SelectAdoptionRequestsSchema)
	.handler(async ({ input }) => {
		return await AdoptionRequestService.create(input)
	})

const updateAdoptionRequests = protectedProcedure()
	.input(z.object({ id: z.uuid(), data: UpdateAdoptionRequestsSchema }))
	.output(SelectAdoptionRequestsSchema)
	.handler(async ({ input }) => {
		return await AdoptionRequestService.update(input.id, input.data)
	})

const deleteAdoptionRequests = protectedProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(z.boolean())
	.handler(async ({ input }) => {
		return await AdoptionRequestService.delete(input.id)
	})

export const adoptionRequests = {
	list: listAdoptionRequests,
	get: getAdoptionRequests,
	create: createAdoptionRequests,
	update: updateAdoptionRequests,
	delete: deleteAdoptionRequests,
}
