import { ORPCError } from '@orpc/server'
import {
	InsertAdoptionRequestsSchema,
	ListAdoptionRequestsSchema,
	SelectAdoptionRequestsSchema,
	UpdateAdoptionRequestsSchema,
} from 'src/lib/validators'
import { z } from 'zod'
import { checkPermissionMiddleware } from '@/lib/permix'
// Generated by @drzl/generator-orpc
// Router for table: adoption_requests
import { AdoptionRequestService } from '@/lib/services/adoption-request-service'
import { protectedProcedure, protectedWithPermissionsProcedure } from '../..'

const listAdoptionRequests = protectedProcedure()
	.input(ListAdoptionRequestsSchema)
	.output(z.array(SelectAdoptionRequestsSchema))
	.handler(async ({ input }) => {
		return await AdoptionRequestService.getAll(input)
	})

const getAdoptionRequests = protectedProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(SelectAdoptionRequestsSchema.nullable())
	.handler(async ({ input }) => {
		return await AdoptionRequestService.getById(input.id)
	})

const createAdoptionRequests = protectedWithPermissionsProcedure()
	.use(checkPermissionMiddleware('adoptionRequests', 'create'))
	.input(InsertAdoptionRequestsSchema)
	.output(SelectAdoptionRequestsSchema)
	.handler(async ({ input }) => {
		return await AdoptionRequestService.create(input)
	})

const updateAdoptionRequests = protectedWithPermissionsProcedure()
	.input(z.object({ id: z.uuid(), data: UpdateAdoptionRequestsSchema }))
	.output(SelectAdoptionRequestsSchema)
	.handler(async ({ input, context }) => {
		const request = await AdoptionRequestService.getById(input.id)

		if (!request) {
			throw new ORPCError('NOT_FOUND')
		}

		if (!context.permix?.check('adoptionRequests', 'update', request)) {
			throw new ORPCError('FORBIDDEN')
		}
		return await AdoptionRequestService.update(input.id, input.data)
	})

const deleteAdoptionRequests = protectedWithPermissionsProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(z.boolean())
	.handler(async ({ input, context }) => {
		const request = await AdoptionRequestService.getById(input.id)

		if (!request) {
			throw new ORPCError('NOT_FOUND')
		}

		if (!context.permix?.check('adoptionRequests', 'delete', request)) {
			throw new ORPCError('FORBIDDEN')
		}
		return await AdoptionRequestService.delete(input.id)
	})

export const adoptionRequests = {
	list: listAdoptionRequests,
	get: getAdoptionRequests,
	create: createAdoptionRequests,
	update: updateAdoptionRequests,
	delete: deleteAdoptionRequests,
}
