import {
	InsertAnimalsSchema,
	SelectAnimalsSchema,
	UpdateAnimalsSchema,
} from 'src/lib/validators'
import { z } from 'zod'
// Generated by @drzl/generator-orpc
// Router for table: animals
import { AnimalService } from '@/lib/services/animal-service'
import { protectedProcedure, publicProcedure } from '../..'

const listAnimals = publicProcedure()
	.output(z.array(SelectAnimalsSchema))
	.handler(async () => {
		return await AnimalService.getAll()
	})

const getAnimals = publicProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(SelectAnimalsSchema.nullable())
	.handler(async ({ input }) => {
		return await AnimalService.getById(input.id)
	})

const createAnimals = protectedProcedure()
	.input(InsertAnimalsSchema)
	.output(SelectAnimalsSchema)
	.handler(async ({ input }) => {
		return await AnimalService.create(input)
	})

const updateAnimals = protectedProcedure()
	.input(z.object({ id: z.uuid(), data: UpdateAnimalsSchema }))
	.output(SelectAnimalsSchema)
	.handler(async ({ input }) => {
		return await AnimalService.update(input.id, input.data)
	})

const deleteAnimals = protectedProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(z.boolean())
	.handler(async ({ input }) => {
		return await AnimalService.delete(input.id)
	})

export const animals = {
	list: listAnimals,
	get: getAnimals,
	create: createAnimals,
	update: updateAnimals,
	delete: deleteAnimals,
}
