import { ORPCError } from '@orpc/server'
import {
	InsertAnimalsSchema,
	SelectAnimalsSchema,
	UpdateAnimalsSchema,
} from 'src/lib/validators'
import { z } from 'zod'
import { checkPermissionMiddleware } from '@/lib/permix'
// Generated by @drzl/generator-orpc
// Router for table: animals
import { AnimalService } from '@/lib/services/animal-service'
import { protectedWithPermissionsProcedure, publicProcedure } from '../..'

const listAnimals = publicProcedure()
	.output(z.array(SelectAnimalsSchema))
	.handler(async () => {
		return await AnimalService.getAll()
	})

const getAnimals = publicProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(SelectAnimalsSchema.nullable())
	.handler(async ({ input }) => {
		return await AnimalService.getById(input.id)
	})

const createAnimals = protectedWithPermissionsProcedure()
	.use(checkPermissionMiddleware('animals', 'create'))
	.input(InsertAnimalsSchema)
	.output(SelectAnimalsSchema)
	.handler(async ({ input }) => {
		return await AnimalService.create(input)
	})

const updateAnimals = protectedWithPermissionsProcedure()
	.input(z.object({ id: z.uuid(), data: UpdateAnimalsSchema }))
	.output(SelectAnimalsSchema)
	.handler(async ({ input, context }) => {
		const animal = await AnimalService.getById(input.id)

		if (!animal) {
			throw new ORPCError('NOT_FOUND')
		}

		if (!context.permix?.check('animals', 'update', animal)) {
			throw new ORPCError('FORBIDDEN')
		}
		return await AnimalService.update(input.id, input.data)
	})

const deleteAnimals = protectedWithPermissionsProcedure()
	.input(z.object({ id: z.uuid() }))
	.output(z.boolean())
	.handler(async ({ input, context }) => {
		const animal = await AnimalService.getById(input.id)

		if (!animal) {
			throw new ORPCError('NOT_FOUND')
		}

		if (!context.permix?.check('animals', 'delete', animal)) {
			throw new ORPCError('FORBIDDEN')
		}

		return await AnimalService.delete(input.id)
	})

export const animals = {
	list: listAnimals,
	get: getAnimals,
	create: createAnimals,
	update: updateAnimals,
	delete: deleteAnimals,
}
