/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AnimalsIndexRouteImport } from './routes/animals/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AnimalsAnimalIdRouteImport } from './routes/animals.$animalId'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsAnimalIdRoute = AnimalsAnimalIdRouteImport.update({
  id: '/animals/$animalId',
  path: '/animals/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/_auth/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/api/$': typeof ApiSplatRoute
  '/animals': typeof AnimalsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/api/$': typeof ApiSplatRoute
  '/animals': typeof AnimalsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animals/$animalId': typeof AnimalsAnimalIdRoute
  '/api/$': typeof ApiSplatRoute
  '/animals/': typeof AnimalsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animals/$animalId'
    | '/api/$'
    | '/animals'
    | '/dashboard'
    | '/api/rpc/$'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animals/$animalId'
    | '/api/$'
    | '/animals'
    | '/dashboard'
    | '/api/rpc/$'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/animals/$animalId'
    | '/api/$'
    | '/animals/'
    | '/dashboard/'
    | '/api/rpc/$'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsAnimalIdRoute: typeof AnimalsAnimalIdRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$animalId': {
      id: '/animals/$animalId'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AnimalsAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsAnimalIdRoute: AnimalsAnimalIdRoute,
  ApiSplatRoute: ApiSplatRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
